language: php
php:
  - '7.2.0'
  - '7.3.0'

git:
  quiet: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer update
  - vendor/bin/codecept build -q

script:
  - vendor/bin/phpcs --standard=PSR.xml src tests/unit tests/functional tests/_support/Helper &&
    codecept run unit,functional --coverage
