language: php
php:
  - '7.2.0'
  - '7.3.0'

git:
  quiet: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# before_install: phpenv config-rm xdebug.ini

install:
  - composer update --no-interaction
  - vendor/bin/codecept build -q

script:
  - vendor/bin/phpcs --standard=PSR1,PSR2 src tests/unit tests/functional &&
    codecept run unit,functional --coverage